"""initial dashboard schema

Revision ID: be5d5ad1093c
Revises:
Create Date: 2026-07-16 18:33:46.748968

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be5d5ad1093c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=False),
        sa.Column("target_id", sa.String(length=160), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False)
    op.create_table(
        "servers",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("region", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("server_id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("template_name", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("status", sa.Enum("online", "offline", "unconfigured", name="agentstatus"), nullable=False),
        sa.Column("telegram_username", sa.String(length=160), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_name"), "agents", ["name"], unique=True)
    op.create_index(op.f("ix_agents_server_id"), "agents", ["server_id"], unique=False)
    op.create_index(op.f("ix_agents_template_name"), "agents", ["template_name"], unique=False)
    op.create_table(
        "activity_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("server_id", sa.String(length=80), nullable=False),
        sa.Column("level", sa.Enum("info", "warn", "error", name="eventlevel"), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_events_agent_id"), "activity_events", ["agent_id"], unique=False)
    op.create_index(op.f("ix_activity_events_created_at"), "activity_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_activity_events_server_id"), "activity_events", ["server_id"], unique=False)
    op.create_table(
        "provision_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_provision_jobs_agent_id"), "provision_jobs", ["agent_id"], unique=False)
    op.create_index(op.f("ix_provision_jobs_status"), "provision_jobs", ["status"], unique=False)
    op.create_table(
        "usage_daily",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("input_tokens", sa.BigInteger(), nullable=False),
        sa.Column("output_tokens", sa.BigInteger(), nullable=False),
        sa.Column("estimated_cost_chf", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "day", name="uq_usage_agent_day"),
    )
    op.create_index(op.f("ix_usage_daily_agent_id"), "usage_daily", ["agent_id"], unique=False)
    op.create_index(op.f("ix_usage_daily_day"), "usage_daily", ["day"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_daily_day"), table_name="usage_daily")
    op.drop_index(op.f("ix_usage_daily_agent_id"), table_name="usage_daily")
    op.drop_table("usage_daily")
    op.drop_index(op.f("ix_provision_jobs_status"), table_name="provision_jobs")
    op.drop_index(op.f("ix_provision_jobs_agent_id"), table_name="provision_jobs")
    op.drop_table("provision_jobs")
    op.drop_index(op.f("ix_activity_events_server_id"), table_name="activity_events")
    op.drop_index(op.f("ix_activity_events_created_at"), table_name="activity_events")
    op.drop_index(op.f("ix_activity_events_agent_id"), table_name="activity_events")
    op.drop_table("activity_events")
    op.drop_index(op.f("ix_agents_template_name"), table_name="agents")
    op.drop_index(op.f("ix_agents_server_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_name"), table_name="agents")
    op.drop_table("agents")
    op.drop_table("servers")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    sa.Enum(name="eventlevel").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="agentstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
